import type { AppStore } from "./types";

const now = "2026-09-25T12:00:00.000Z";

export const SEED: AppStore = {
  voiceProfiles: [
    {
      id: "voice-v1",
      name: "Aivora Voice v1",
      version: "v1",
      description:
        "Femenina, ~25 años, cálida, habanera suave, cercana, natural, expresiva sin teatralidad.",
      params: "ElevenLabs — tono conversacional, español cubano suave",
    },
  ],
  identity: {
    id: "aivora-1",
    name: "Aivora",
    age: 25,
    nationality: "Cubana",
    originCity: "La Habana",
    bio: "Creadora virtual cubana creada con inteligencia artificial. Su condición de creadora virtual forma parte de su identidad.",
    transparencyNote:
      "Siempre debe quedar claro que Aivora es IA. No ocultar su naturaleza virtual.",
    activeVersionId: "id-v1",
    versions: [
      {
        id: "id-v1",
        version: "v1",
        createdAt: now,
        changelog: "Identidad canónica inicial",
        appearance: {
          face: "Rostro ovalado, rasgos suaves, proporciones naturales, joven adulta.",
          eyes: "Almendrados, verde oliva / avellana, destellos dorados.",
          eyebrows: "Castaño medio, naturales, ligeramente arqueadas.",
          nose: "Recta, pequeña, proporcionada.",
          lips: "Carnosos, rosa natural.",
          skin: "Clara, subtono cálido, textura realista, poros visibles, pecas suaves en nariz y mejillas.",
          hair: "Castaño hasta los hombros, ondulado, volumen medio, raya ligeramente lateral, mechas cálidas miel/doradas.",
          body: "Delgada-atlética, femenina, natural y proporcionada. Cintura definida, caderas redondeadas, busto lleno natural. Atractiva ≠ artificial.",
          realism:
            "Fotorealismo alto: piel con textura, poros, imperfecciones leves, iluminación creíble. Evitar piel plástica, CGI, AI beauty face genérico.",
        },
        personality: {
          traits: [
            "cálida",
            "auténtica",
            "empática",
            "curiosa",
            "ligeramente soñadora",
            "tranquila",
            "segura",
            "cercana",
          ],
          tone: "Conversacional, relajado, seguro. Humor cubano suave y espontáneo.",
          speech:
            "Español cubano / habanero natural. Expresiones como «mi vida», «un momentico», «mira», «bueno...» sin exagerar cubanismos.",
          expressions: ["mi vida", "un momentico", "mira", "bueno..."],
          limits: [
            "No parecer chatbot",
            "No presentadora corporativa",
            "No excesivamente perfecta",
            "No artificialmente alegre",
            "No exageradamente seductora",
            "No caricatura de cubana",
          ],
        },
        voiceProfileId: "voice-v1",
      },
    ],
  },
  references: [
    {
      id: "ref-face-01",
      title: "Rostro canónico — frontal",
      category: "Face",
      status: "Canonical",
      notes: "Referencia maestra de rostro",
      createdAt: now,
    },
    {
      id: "ref-body-01",
      title: "Cuerpo canónico — cuerpo completo",
      category: "Body",
      status: "Canonical",
      notes: "Proporciones oficiales",
      createdAt: now,
    },
    {
      id: "ref-hair-01",
      title: "Cabello ondulado castaño",
      category: "Hair",
      status: "Canonical",
      createdAt: now,
    },
    {
      id: "ref-outfit-007",
      title: "Outfit #007 — short + blusa casa",
      category: "Outfit",
      status: "Canonical",
      notes: "Outfit para escenas domésticas",
      createdAt: now,
    },
    {
      id: "ref-acc-chain",
      title: "Cadena A + aretes B",
      category: "Accessories",
      status: "Canonical",
      createdAt: now,
    },
    {
      id: "ref-env-home",
      title: "Casa moderna — interior",
      category: "Environment",
      status: "Canonical",
      createdAt: now,
    },
  ],
  products: [
    {
      id: "prod-fan-003",
      name: "Ventilador portátil recargable",
      sku: "FAN-003",
      description:
        "Ventilador personal blanco con asa, batería recargable y flujo de aire ajustable.",
      specs: [
        "3 velocidades",
        "Batería recargable USB-C",
        "Silencioso",
        "Asa integrada",
      ],
      colors: ["Blanco", "Gris claro"],
      dimensions: "Approx. 20 × 10 × 8 cm",
      claims: [
        "Alivio del calor en casa",
        "Portátil para trabajo o descanso",
        "No inventar botones o luces inexistentes",
      ],
      visualDetails: [
        "Cuerpo blanco mate",
        "Rejilla frontal redonda",
        "Botón de control central",
        "Base estable",
      ],
      assetIds: ["pa-fan-1"],
      createdAt: now,
    },
  ],
  productAssets: [
    {
      id: "pa-fan-1",
      productId: "prod-fan-003",
      label: "Foto real — frontal",
    },
  ],
  ideas: [
    {
      id: "idea-01",
      title: "Ventilador en día caluroso",
      concept:
        "Aivora muestra cómo un ventilador portátil hace más cómodo un día caluroso en casa.",
      formatHint: "reel",
      campaignHint: "Campaña ventilador septiembre",
      status: "converted",
      createdAt: now,
      productionId: "prod-001",
    },
    {
      id: "idea-02",
      title: "Presentación en el Malecón",
      concept:
        "Aivora se presenta como creadora virtual desde el Malecón habanero al atardecer.",
      formatHint: "fotografia",
      status: "ready",
      createdAt: now,
    },
    {
      id: "idea-03",
      title: "Café y rutina de creación",
      concept:
        "Escena cotidiana: Aivora en un café planificando contenido para la semana.",
      formatHint: "carrusel",
      status: "draft",
      createdAt: now,
    },
  ],
  productions: [
    {
      id: "prod-001",
      title: "Reel ventilador — día caluroso",
      type: "reel",
      status: "REVIEW",
      ideaId: "idea-01",
      campaignId: "camp-01",
      identityLock: {
        characterName: "Aivora",
        identityVersionId: "id-v1",
        faceRefId: "ref-face-01",
        bodyRefId: "ref-body-01",
        hairRefId: "ref-hair-01",
        outfitRefId: "ref-outfit-007",
        accessoryRefIds: ["ref-acc-chain"],
        productId: "prod-fan-003",
        environmentRefId: "ref-env-home",
        voiceProfileId: "voice-v1",
        personalityNote: "Canon Aivora — cálida, cercana, transparente como IA",
        notes: "Misma cadena y outfit en las 5 escenas",
      },
      sceneIds: ["scene-01", "scene-02", "scene-03", "scene-04", "scene-05"],
      createdAt: now,
      updatedAt: now,
    },
  ],
  scenes: [
    {
      id: "scene-01",
      productionId: "prod-001",
      order: 1,
      title: "Introducción",
      description: "Aivora saluda en casa y menciona el calor del día.",
      camera: "Plano medio, ligero contraluz suave",
      pose: "De pie, relajada",
      expression: "Sonrisa cálida",
      dialogue: "Mira, hoy está que arde… un momentico y te muestro algo.",
      durationSec: 3,
    },
    {
      id: "scene-02",
      productionId: "prod-001",
      order: 2,
      title: "Producto",
      description: "Presenta el ventilador portátil con claridad.",
      camera: "Plano corto producto + manos",
      pose: "Sujeta el ventilador frente a cámara",
      expression: "Atenta, explicativa",
      dialogue: "Este ventiladorcito me salva la tarde en casa.",
      durationSec: 4,
    },
    {
      id: "scene-03",
      productionId: "prod-001",
      order: 3,
      title: "Interacción",
      description: "Enciende el ventilador y siente el aire.",
      camera: "Plano medio",
      pose: "Cerca del sofá / mesa",
      expression: "Alivio genuino",
      durationSec: 4,
    },
    {
      id: "scene-04",
      productionId: "prod-001",
      order: 4,
      title: "Demostración",
      description: "Muestra portabilidad y uso cotidiano.",
      camera: "Travelling corto",
      pose: "Camina con el ventilador en la mano",
      expression: "Natural, cercana",
      durationSec: 4,
    },
    {
      id: "scene-05",
      productionId: "prod-001",
      order: 5,
      title: "Cierre",
      description: "Cierra con CTA suave y transparencia de creadora IA.",
      camera: "Plano medio frontal",
      expression: "Sonrisa cercana",
      dialogue: "Si te sirve, guárdalo. Soy Aivora, tu creadora virtual.",
      durationSec: 3,
    },
  ],
  prompts: [],
  generatedAssets: [
    {
      id: "gen-001",
      productionId: "prod-001",
      sceneId: "scene-02",
      kind: "image",
      dataUrl: "",
      fileName: "placeholder-scene-02.jpg",
      createdAt: now,
      reviewId: "rev-001",
    },
  ],
  reviews: [
    {
      id: "rev-001",
      productionId: "prod-001",
      assetId: "gen-001",
      checklist: {
        face: true,
        body: true,
        hair: true,
        outfit: true,
        accessories: false,
        product: true,
        environment: true,
        continuity: true,
        voice: true,
        quality: true,
      },
      decision: "PENDING",
      notes: "Pendiente: verificar cadena A en el cuello",
      createdAt: now,
    },
  ],
  library: [
    {
      id: "lib-seed-01",
      productionId: "prod-001",
      sceneId: "scene-02",
      assetId: "gen-001",
      kind: "image",
      dataUrl: "",
      fileName: "aivora-ventilador-demo.jpg",
      tags: ["reel", "ventilador", "casa"],
      productId: "prod-fan-003",
      approvedAt: now,
    },
  ],
  campaigns: [
    {
      id: "camp-01",
      title: "Campaña — Ventilador septiembre",
      objective: "Promocionar el ventilador portátil con contenido cotidiano en casa.",
      status: "active",
      productionIds: ["prod-001"],
      publicationIds: ["pub-01"],
      productId: "prod-fan-003",
      startDate: "2026-09-20",
      endDate: "2026-09-30",
      createdAt: now,
    },
  ],
  calendarItems: [
    {
      id: "cal-01",
      title: "Reel ventilador — IG",
      date: "2026-09-26T10:00:00.000Z",
      platform: "instagram",
      format: "reel",
      libraryAssetId: "lib-seed-01",
      publicationId: "pub-01",
      campaignId: "camp-01",
      notes: "Publicar en Stories + feed",
      createdAt: now,
    },
    {
      id: "cal-02",
      title: "Same asset — TikTok",
      date: "2026-09-27T18:00:00.000Z",
      platform: "tiktok",
      format: "video",
      libraryAssetId: "lib-seed-01",
      publicationId: "pub-02",
      campaignId: "camp-01",
      createdAt: now,
    },
  ],
  publications: [
    {
      id: "pub-01",
      title: "Aivora + ventilador en casa",
      platform: "instagram",
      status: "scheduled",
      scheduledAt: "2026-09-26T10:00:00.000Z",
      libraryAssetId: "lib-seed-01",
      productionId: "prod-001",
      campaignId: "camp-01",
      caption:
        "Mira, hoy está que arde… este ventiladorcito me salva la tarde. Soy Aivora, tu creadora virtual 💜",
      createdAt: now,
    },
    {
      id: "pub-02",
      title: "Aivora + ventilador — TikTok",
      platform: "tiktok",
      status: "draft",
      scheduledAt: "2026-09-27T18:00:00.000Z",
      libraryAssetId: "lib-seed-01",
      productionId: "prod-001",
      campaignId: "camp-01",
      caption: "Día caluroso en casa con Aivora (sí, soy IA).",
      createdAt: now,
    },
    {
      id: "pub-03",
      title: "Presentación Malecón (histórico)",
      platform: "instagram",
      status: "published",
      scheduledAt: "2026-09-20T09:00:00.000Z",
      publishedAt: "2026-09-20T09:02:00.000Z",
      caption: "Hola, soy Aivora. Creadora virtual desde La Habana.",
      createdAt: now,
    },
  ],
  metrics: [
    {
      id: "met-01",
      publicationId: "pub-03",
      platform: "instagram",
      views: 48200,
      reach: 39100,
      likes: 3200,
      comments: 214,
      shares: 98,
      saves: 410,
      followersGained: 186,
      engagementRate: 8.4,
      updatedAt: now,
    },
    {
      id: "met-02",
      publicationId: "pub-01",
      platform: "instagram",
      views: 0,
      reach: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      saves: 0,
      followersGained: 0,
      engagementRate: 0,
      updatedAt: now,
    },
  ],
  team: [
    {
      id: "team-01",
      name: "Admin",
      email: "admin@aivora.studio",
      role: "Owner",
      active: true,
      createdAt: now,
    },
    {
      id: "team-02",
      name: "Revisor creativo",
      email: "review@aivora.studio",
      role: "Reviewer",
      active: true,
      createdAt: now,
    },
  ],
  settings: {
    studioName: "Aivora Studio",
    defaultLanguage: "es-CU",
    defaultPlatform: "instagram",
    transparencyRequired: true,
    requireReviewBeforeLibrary: true,
    requireLibraryBeforePublish: true,
    preferredTools: ["gemini_image", "gemini_video", "higgsfield"],
    socialHandles: {
      instagram: "@aivora.creators",
      tiktok: "@aivora.creators",
      youtube: "Aivora Creators",
      facebook: "Aivora Creators",
    },
    notes: "MVP local · generación externa · Identity Lock obligatorio",
  },
};
